#
# The app proxy
#
---
#
# Deploy the pods
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-backend
  namespace: default
  labels:
    app: app-backend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  revisionHistoryLimit: 10
  template:
    metadata:
      name: app-backend
      namespace: default
      labels:
        app: app-backend
    spec:
      containers:
      - image: "teamdigitale/italia-backend:v0.0.6"
        name: app-backend
        ports:
        - name: http-port
          containerPort: 80
        env:
        - name: "NODE_ENV"
          value: "production"
        - name: "API_URL"
          value: "https://agid-apim-test.azure-api.net/api/v1"
        - name: "SAML_CALLBACK_URL"
          value: "https://app-backend.k8s.test.cd.teamdigitale.it/assertionConsumerService"
        - name: "SAML_ISSUER"
          value: "https://spid.agid.gov.it/cd"
        - name: "API_KEY"
          valueFrom:
            secretKeyRef:
              name: app-backend-secrets
              key: api_key
        volumeMounts:
          - name: certs
            mountPath: "/usr/src/app/certs"
            readOnly: true
        livenessProbe:
          httpGet:
            path: "/ping"
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 5
      - image: wodby/redis:4.0
        name: redis
        ports:
        - name: redis-port
          containerPort: 6379
        env:
        - name: "REDIS_TIMEOUT"
          value: "300"
        - name: "REDIS_TCP_KEEPALIVE"
          value: "60"
        - name: "REDIS_MAXMEMORY"
          value: "182m"
      volumes:
      - name: certs
        secret:
          # cert.pem, key.pem
          secretName: spid-cert

---
#
# A service exposing the app to the cluster.
#
apiVersion: v1
kind: Service
metadata:
  name: app-backend
  namespace: default
spec:
  selector:
    app: app-backend
  ports:
    - protocol: TCP
      port: 80
