#
# The project landing page
#
---
#
# Deploy the pods
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-landing
  namespace: default
  labels:
    app: app-landing
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  revisionHistoryLimit: 10
  template:
    metadata:
      name: app-landing
      namespace: default
      labels:
        app: app-landing
    spec:
      containers:
      - image: "teamdigitale/io-landing:website-v151"
        name: app-landing
        ports:
        - name: http-port
          containerPort: 80
---
#
# A service exposing the app-landing pod to the cluster.
#
apiVersion: v1
kind: Service
metadata:
  name: app-landing
  namespace: default
spec:
  selector:
    app: app-landing
  ports:
    - protocol: TCP
      port: 80
